### ISSUE TITLE
Crash while dismissing Dialog after inserting a new task

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Kofil/moloko#32]
```
java.lang.IllegalArgumentException: View not attached to window manager
    at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:355)
    at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:200)
    at android.view.Window$LocalWindowManager.removeView(Window.java:432)
    at android.app.Dialog.dismissDialog(Dialog.java:278)
    at android.app.Dialog.access$000(Dialog.java:71)
    at android.app.Dialog$1.run(Dialog.java:111)
    at android.app.Dialog.dismiss(Dialog.java:268)
    at dev.drsoran.moloko.util.AsyncInsertEntity.onPostExecute(AsyncInsertEntity.java:165)
    at dev.drsoran.moloko.util.AsyncInsertEntity.onPostExecute(AsyncInsertEntity.java:1)
    at android.os.AsyncTask.finish(AsyncTask.java:417)
    at android.os.AsyncTask.access$300(AsyncTask.java:127)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:143)
    at android.app.ActivityThread.main(ActivityThread.java:4717)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
    at dalvik.system.NativeStart.main(Native Method)


```

Original issue reported on code.google.com by `ronny.roehricht` on 19 Jul 2011 at 8:50

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r451.
```

Original comment by `ronny.roehricht` on 31 Jul 2011 at 10:11
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Reopened cause I missed some dialogs to set owner Activity.
```

Original comment by `ronny.roehricht` on 8 Aug 2011 at 6:52
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronny.roehricht` on 3 Oct 2011 at 2:49
- Added labels: **Milestone-Beta-0.16.0**
- Removed labels: **Beta-0.15.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronny.roehricht` on 9 Oct 2011 at 4:00
- Changed state: **NotYetReleased**

**Comment by GoogleCodeExporter** [comment]
Original comment by `ronny.roehricht` on 22 Jan 2012 at 3:16
- Changed state: **Fixed**
